### ISSUE TITLE
Removed iconv + persisting empty value error

### ISSUE THREAD

**Issue by robiso** [wdj-ac/wondercms#7]
After a couple of days of thinking, here's an update to the index.php. What's new?

- removed iconv to avoid losing some special charaters
  - some of the characters (Russian, Chinese, Japanase, Latin) were not converted by the iconv function, because it does not have substitutes for these letters.

Trying to transliterate all of these mentioned languages and all other special high end unicode characters would take up a couple of WonderCMS sizes in terms of code. This means URLs will not be fully slugified, as modern browsers are also starting to display these characters properly, we'll simply stop worrying about converting them, and display as the users enters them like it works now.

We're still going to use your menu function, only shortened as displayed below and without set locale, as it's not necessary.

## The persisting error
 - `PHP Warning:  Creating default object from empty value in index.php on line 122`
I figured out when this happens (with the latest **unofficial** 2.1.0 index.php below + your empty slug fix).

### Error example:
 1. Go to http://yourSite.com/NEW PAGE
 2. Error shows up in error log.
This only happens when there's is a space between NEW**empty space**PAGE as visiting http://yourSite.com/NEWPAGE doesn't trigger this.

Everything else seems fine. I'll additionally test this version in different environments. 
[index.php.zip](https://github.com/wdj-ac/wondercms/files/975002/index.php.zip)

Edit: I see the above error happens in all others versions of WonderCMS, so looks like this isn't caused by your code. Trying to figure out why this goes wrong before publishing 2.1.0 with @wdj-ac additions.
I would still wait before adding hooks with version 2.1.0.

**Comment by nightillusions** [comment]
> We're still going to use your menu function, only shortened as displayed below and without set locale, as it's not necessary.

If you wish, I change my code with your improvements, so that the pull request is ready to merge.

> I see the above error happens in all others versions of WonderCMS, so looks like this isn't caused by your code. 

Here is your code with a little workaround. The extra condition for $currentPageExists, is to prevent the "duplicate content" problem (SEO). What do you think?
[index_.zip](https://github.com/wdj-ac/wondercms/files/976622/index_.zip)

> I would still wait before adding hooks with version 2.1.0.

Okay. I exclude the hook priorities in this branch.

**Comment by robiso** [comment]
@wdj-ac bingo! With slugifying the function url, the "empty error (`PHP Warning: Creating default object from empty value in index.php on line 122)`" is fixed. Some additional changes were necessary:
 - changed the slugify function to use htmlspecialchars to prevent XSS injections in the URL. I didn't include the new function check, because this is redundant as far as I understand?

I didn't notice a duplicate content problems, can you please elaborate?

This version hit's the nail in terms of error free and I couldn't break it, you're awesome! The latest index: 
[index.php.zip](https://github.com/wdj-ac/wondercms/files/977747/index.php.zip)

**Comment by robiso** [comment]
We can close this issue as the empty value error is completely gone. Let me know how I can run into / test the SEO duplicate you mentioned.

I suggest the last issue mentioned here: https://github.com/wdj-ac/wondercms/issues/8 should be built/fixed on the last best index.php version posted above (https://github.com/wdj-ac/wondercms/files/977747/index.php.zip)

**Comment by nightillusions** [comment]
> changed the slugify function to use htmlspecialchars to prevent XSS injections in the URL

👍 

> changed the slugify function to use htmlspecialchars to prevent XSS injections in the URL. I didn't include the new function check, because this is redundant as far as I understand?

What do you think about doing it on the right way and using a map to transform the characters? It is of course more code, but this will do it´s job in every scenario.
I found a nice map here: https://github.com/keyvanakbary/slugifier
Implemented here: 
[index_extended_slugifier.zip](https://github.com/wdj-ac/wondercms/files/979485/index_extended_slugifier.zip)

> I didn't notice a duplicate content problems, can you please elaborate?

When you add a new page via url like this: `www.yoursite.com/simple%20test`
The slug in the database is this: `www.yoursite.com/simple-test`
As a logged in admin, theres no problem that the system navigates you to the page in the database with slug `simple-test`. Maybe this is even a feature to prevent collision when creating pages via url instead of using the new "add page" button. 
The problem is: Search-Engines don´t like it. Because there is the same content with two different URLs, it COULD causes trouble in the search results. So before getting into trouble we should prevent this :-)
As a visitor we get a 404 Error for the URL with %20 inside.
More: https://support.google.com/webmasters/answer/66359?hl=en

**Comment by robiso** [comment]
I really tried thinking this through, and it made sense to me to leave them as they were. I've seen that exact function but I don't think it covers all scenarios such as Chinese, Japan? I've checked out how WordPress goes about this and it gets even more complex as they iterate through differents sets of characters.

> When you add a new page via url like this: www.yoursite.com/simple%20test
The slug in the database is this: www.yoursite.com/simple-test
As a logged in admin, theres no problem that the system navigates you to the page in the database with slug simple-test. Maybe this is even a feature to prevent collision when creating pages via url instead of using the new "add page" button.
The problem is: Search-Engines don´t like it. Because there is the same content with two different URLs, it COULD causes trouble in the search results. So before getting into trouble we should prevent this :-)
As a visitor we get a 404 Error for the URL with %20 inside.

If you create a page like you said
yourpage.com/test page, yourpage.com/test-page is created. If the search engine visits yourpage.com/test%20page - the page does not exist.
This is how the function url works, it's also slugified so the search engine doesn't see double content because it doesn't exist as far as my testing goes.

Can anyone else share their opinion on covering all charsets?

**Comment by nightillusions** [comment]
> I've checked out how WordPress goes about this and it gets even more complex as they iterate through differents sets of characters.

Yes I´ve also checked the `remove_accents()` from WordPress. It is huge, but it seems the only "easy" way to covers all scenarios. I don´t think that we need to cover all of this.

> This is how the function url works

It´s because I implemented this part for "search-engines":

`if (isset($_GET['page']) && ! wCMS::$loggedIn) if (wCMS::$currentPage !== $_GET['page']) wCMS::$currentPageExists = false;`

**Comment by robiso** [comment]
WonderCMS has been published in one Japanese website, and I think if we can't cover all scenarios (especially such large potential audiences such as Japan, China) with something simple and small, we can leave the slugs as they were up to now (with a big of cleaning like you've provided) and leave them as the user enters them in the menu.

I didn't include that part of your code in the latest index.  We already serve 404s to search engines in cases where the page doesn't exist, and we also don't have to worry about yourpage.com/test%20page as the user would manually have to share it for someone to get to the %20 and the menu already uses the slug functionality. The space in the URL never exists so the search engine gets a 404 page, but like I mentioned, the user would manually have to share the %20 URL once he created it.

**Comment by robiso** [comment]
Closing this issue for now because the issue is solved, but I would love to continue discussing this. I also dislike seeing Issues on a project, so I'm saving you from the same thing :grin:
